### PR TITLE
Add linting proposal

### PR DESCRIPTION
**Pull request by curtisblackwell**
## Author checklist
- [x] I'm proposing a single change in this PR.
- I believe the proposed standard:
  - [x] benefits more than it costs us and
  - [x] doesn't conflict with our people-first value.
- [x] The standard's file(s) follow(s) [the established directory structure][directory-structure].
- I provided:
  - [x] a succinct summary,
  - [x] reasoning for the proposed change,
  - [x] an example/instructions on how to embody the standard unless repealing, and
  - [x] a longer explanation if appropriate.

*Check boxes if requirement met or irrelevant.*

## First reviewer checklist
***NOTE:** Some of the author's checklist items are intentionally omitted, because they are a matter of opinion and up for discussion with the whole team.*

- [x] This PR contains a single change.
- [x] The proposed standard follows [the established directory structure][directory-structure].
- The author provided:
  - [x] a succinct summary,
  - [x] reasoning for the proposed change, and
  - [x] an example/instructions on how to embody the standard unless repealing.

*Check boxes if requirement met or irrelevant.*

[directory-structure]: ../tree/master/standards#directory-structure

### CODE REVIEW

**Comment by JHWelch** [comment]
Are there specific settings that we prefer for the Linters? Or just using the default settings?

**Comment by curtisblackwell** [comment]
@JHWelch Specific settings. That's what "should probably include a linter config for ESLint" is about.

This isn't really ready for review, it was just part of my rock to have an example proposal. I need to set time aside to figure more out for this. I'm half considering Prettier, but it looks like it does some things that makes it harder to read code in some fairly common cases. So… probably gonna suggest we adopt an existing ESLint config and tweak as desired.

**Comment by curtisblackwell** [comment]
@JHWelch can you skim this and take care of the First Reviewer Checklist in the first comment?

**Comment by curtisblackwell** [comment]
Open for voting.

**Pull request merged**
